FROM ruby:3.2.2-slim

# Install PostgreSQL client and other dependencies
RUN apt-get update -qq && \
    apt-get install -y postgresql-client libpq-dev build-essential \
    libgeos-dev libproj-dev libgdal-dev

# Set working directory
WORKDIR /app

# Copy Gemfile and install dependencies
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the rest of the application
COPY . . 