# fly.toml app configuration file generated for click-camp on 2025-01-21T18:18:31-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'click-camp'
primary_region = 'lax'
console_command = '/rails/bin/rails console'

[build]

[processes]
  app = './bin/rails server -b 0.0.0.0'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
